{
 "title": "Ditto",
 "description": "Ditto application performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "postgres", "label": "Postgres", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "description": "Responses sent back to users from the server. Organized by status code.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(ditto_http_responses_total{status=~\"5..\",path!=\"/relay\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} ({{status}})"
    },
    {
     "expr": "increase(ditto_http_responses_total{status=~\"4..\",path!=\"/relay\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} ({{status}})"
    },
    {
     "expr": "increase(ditto_http_responses_total{status=~\"3..\",path!=\"/relay\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} ({{status}})"
    },
    {
     "expr": "increase(ditto_http_responses_total{status=~\"2..\",path!=\"/relay\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}} ({{status}})"
    }
   ]
  },
  {
   "title": "Database Available Connections",
   "type": "gauge",
   "description": "Number of idle database connections available to the server. Higher is better. At 0, the site stops working.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ditto_db_available_connections", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Database Effort",
   "type": "timeseries",
   "description": "How hard the database is working on a per-query basis. It's query time divided by number of queries. Lower is better.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "rate(ditto_db_query_duration_ms_sum[$__rate_interval]) / rate(ditto_db_queries_total[$__rate_interval])",
     "legendFormat": "Effort"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "timeseries",
   "description": "Number of individual database calls.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "increase(ditto_db_queries_total[$__rate_interval])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Policy Events",
   "type": "timeseries",
   "description": "Number of Nostr events that are accepted or rejected by the custom policy script.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(ditto_policy_events_total{ok=\"true\"}[$__rate_interval])",
     "legendFormat": "Accept"
    },
    {
     "expr": "increase(ditto_policy_events_total{ok=\"false\"}[$__rate_interval])",
     "legendFormat": "Reject"
    }
   ]
  },
  {
   "title": "Relay Connections",
   "type": "timeseries",
   "description": "Total number of Nostr clients currently connected to the Nostr relay.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "targets": [
    { "expr": "ditto_relay_connections", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Database Query Time",
   "type": "timeseries",
   "description": "Sum duration of all queries in milliseconds.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(ditto_db_query_duration_ms_sum[$__rate_interval])",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Query Performance",
   "type": "table",
   "description": "SQL queries ranked by total time.",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH query_stats AS (\n  SELECT\n    LEFT(query, 10000) AS query,\n    (total_plan_time + total_exec_time) AS total_time,\n    (mean_plan_time + mean_exec_time) AS average_time,\n    (max_plan_time + max_exec_time) AS max_time,\n    calls\n  FROM\n    pg_stat_statements\n  WHERE\n    calls > 0\n)\nSELECT\n  query,\n  total_time,\n  average_time,\n  max_time,\n  calls,\n  total_time / (SELECT SUM(total_time) FROM query_stats) AS total_percent\nFROM\n  query_stats\nORDER BY\n  total_time DESC\nLIMIT 100;\n"
    }
   ]
  },
  {
   "title": "Index Uses",
   "type": "table",
   "description": "Index hit rate. Higher is better.",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n    relname AS table,\n    indexrelname AS index,\n    (idx_blks_hit * 100) / (CASE WHEN idx_blks_hit + idx_blks_read = 0 THEN 1 ELSE idx_blks_hit + idx_blks_read END) as percentage_used\nFROM \n    pg_statio_user_indexes\nWHERE \n    schemaname = 'public'\nORDER BY\n    percentage_used DESC;"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "piechart",
   "description": "Size of database tables.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  c.relname AS table,\n  pg_table_size(c.oid) AS size\nFROM\n  pg_class c\n  LEFT JOIN pg_namespace n ON (n.oid = c.relnamespace)\nWHERE\n  n.nspname NOT IN ('pg_catalog', 'information_schema')\n  AND n.nspname !~ '^pg_toast'\n  AND c.relkind IN ('r', 'm')\nORDER BY\n  pg_table_size(c.oid) DESC;"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "piechart",
   "description": "Size of all indexes in the database.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  c.relname AS name,\n  sum(c.relpages :: bigint * 8192) :: bigint AS size\nFROM\n  pg_class c\n  LEFT JOIN pg_namespace n ON (n.oid = c.relnamespace)\nWHERE\n  n.nspname NOT IN ('pg_catalog', 'information_schema')\n  AND n.nspname !~ '^pg_toast'\n  AND c.relkind = 'i'\nGROUP BY\n  (n.nspname, c.relname)\nORDER BY\n  sum(c.relpages) DESC;"
    }
   ]
  },
  {
   "title": "Unused Indexes",
   "type": "table",
   "description": "Indexes that are not used or very rarely used.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS table,\n  indexrelname AS index,\n  pg_relation_size(i.indexrelid) AS index_size,\n  idx_scan as index_scans\nFROM\n  pg_stat_user_indexes ui\n  JOIN pg_index i ON ui.indexrelid = i.indexrelid\nWHERE\n  NOT indisunique\n  AND idx_scan < 50\n  AND pg_relation_size(relid) > 5 * 8192\nORDER BY\n  pg_relation_size(i.indexrelid) / nullif(idx_scan, 0) DESC NULLS FIRST,\n  pg_relation_size(i.indexrelid) DESC;"
    }
   ]
  },
  {
   "title": "Relay Messages",
   "type": "timeseries",
   "description": "Nostr messages sent to the relay over WebSocket.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(ditto_relay_messages_total[$__rate_interval])",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Pipeline Events",
   "type": "timeseries",
   "description": "Nostr events from all sources. Organized by kind.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(ditto_pipeline_events_total[$__rate_interval])",
     "legendFormat": "Kind {{kind}}"
    }
   ]
  },
  {
   "title": "Event Sources",
   "type": "timeseries",
   "description": "Rate of events being processed by different parts of the application.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(increase(ditto_pipeline_events_total[$__rate_interval]))",
     "legendFormat": "Pipeline Events"
    },
    {
     "expr": "sum(increase(ditto_relay_events_total[$__rate_interval]))",
     "legendFormat": "Relay Events"
    },
    {
     "expr": "sum(increase(ditto_firehose_events_total[$__rate_interval]))",
     "legendFormat": "Firehose Events"
    }
   ]
  }
 ]
}