/**
 * Ditto's visual state, in the words the kit's renderer draws a V3 Blobbi in.
 *
 * V1 Blobbis get their faces from the recipe pipeline (recipe.ts), which finds
 * the V1 artwork's eyes and mouth in its SVG and rewrites them. A V3 drawing
 * is generated by the kit and is not that markup, so nothing here touches SVG:
 * a recipe is read for what it MEANS (a frown, raised brows, half-closed eyes)
 * and handed to the renderer as its own expression parts, which it draws on
 * the individual's own face.
 *
 * What the kit has no word for is dropped on V3, not imitated: star and spiral
 * pupils, tears, drool, food icons, dirt, stink clouds and the anger fill.
 */

import type {
  BlobbiBlushState,
  BlobbiBrowState,
  BlobbiEggCrack,
  BlobbiExpressionParts,
  BlobbiEyeState,
  BlobbiMouthState,
} from '@blobbi-kit/renderer';

import type { EggTourVisualState } from '@/blobbi/egg';

import type { BlobbiEmotion } from './emotion-types';
import { resolveVisualRecipe, type BlobbiVisualRecipe } from './recipe';

function eyesOf(recipe: BlobbiVisualRecipe): BlobbiEyeState {
  const eyes = recipe.eyes;
  if (!eyes) return 'open';
  if (eyes.sleepingClosed || eyes.happyArc) return 'closed';
  if (eyes.sleepyBlink) return 'half';
  if (eyes.starEyes || eyes.dizzySpirals) return 'wide';
  return 'open';
}

function mouthOf(recipe: BlobbiVisualRecipe): BlobbiMouthState {
  const mouth = recipe.mouth;
  if (!mouth) return 'neutral';
  if (mouth.sadMouth) return 'frown';
  if (mouth.roundMouth || mouth.eatingMouth || mouth.chewingMouth) return 'open';
  if (mouth.bigSmile) return 'grin';
  if (mouth.smallSmile) return 'smile';
  if (mouth.droopyMouth || mouth.sleepyMouth) return 'flat';
  return 'neutral';
}

function browsOf(recipe: BlobbiVisualRecipe): BlobbiBrowState {
  const brows = recipe.eyebrows;
  if (!brows) return 'neutral';
  const config = brows.config;
  // A positive angle tilts the inner ends down: cross, irritated, scheming.
  if (config && config.angle >= 8) return 'lowered';
  if (brows.animated?.enabled) return 'raised';
  if (config && config.angle < 0) {
    // Inner ends up: high on the forehead reads surprised, low reads worried.
    return (config.offsetY ?? 0) <= -11 ? 'raised' : 'inner-up';
  }
  return 'neutral';
}

function blushOf(recipe: BlobbiVisualRecipe): BlobbiBlushState {
  if (recipe.mouth?.sadMouth || recipe.eyes?.wateryEyes?.includeWaterFill) return 'none';
  if (recipe.mouth?.bigSmile || recipe.eyes?.happyArc) return 'strong';
  return 'soft';
}

/** The expression a V3 Blobbi wears for a resolved recipe. */
export function recipeToV3Expression(recipe: BlobbiVisualRecipe): Required<BlobbiExpressionParts> {
  return {
    eyes: eyesOf(recipe),
    mouth: mouthOf(recipe),
    brows: browsOf(recipe),
    blush: blushOf(recipe),
  };
}

/**
 * The expression for whichever of Ditto's two inputs is in play: a recipe
 * wins, as it does for V1; otherwise the named emotion's own recipe.
 */
export function resolveV3Expression(
  recipe: BlobbiVisualRecipe | undefined,
  emotion: BlobbiEmotion = 'neutral',
): Required<BlobbiExpressionParts> {
  if (!recipe && emotion === 'happy') {
    // Ditto's V1 'happy' recipe is empty because the V1 face already smiles;
    // the V3 face is neutral at rest, so say it.
    return { eyes: 'open', mouth: 'smile', brows: 'raised', blush: 'soft' };
  }
  return recipeToV3Expression(recipe ?? resolveVisualRecipe(emotion));
}

/** The kit's crack overlay for the hatching tour's egg state. */
export function eggCrackForTourState(state: EggTourVisualState | undefined): BlobbiEggCrack {
  switch (state) {
    case 'crack_stage_1':
      return 'light';
    case 'crack_stage_2':
      return 'medium';
    case 'crack_stage_3':
    case 'opening':
    case 'hatching':
      return 'heavy';
    default:
      return 'none';
  }
}
